### ISSUE TITLE
resize filter not available on macos

### ISSUE THREAD

**Issue by andresmntr** [ShiftMediaProject/x264#11]
Filtering:

      --vf, --video-filter <filter0>/<filter1>/... Apply video filtering to the input file

      Filter options may be specified in <filter>:<option>=<value> format.

      Available filters:
      crop:left,top,right,bottom
            removes pixels from the edges of the frame
      select_every:step,offset1[,...]
            apply a selection pattern to input frames
            step: the number of frames in the pattern
            offsets: the offset into the step to select a frame
            see: http://avisynth.nl/index.php/Select#SelectEvery

**Comment by Sibras** [comment]
This is the wrong place for issues with macos. For general issues you want to go to the main x264 project.
