### ISSUE TITLE
libx264.lib(analyse.obj) : error LNK2001: unresolved external symbol __ultof3

### ISSUE THREAD

**Issue by JiaPai12138** [ShiftMediaProject/x264#13]
I am trying to link libx264.lib (release [0.164.r3194](https://github.com/ShiftMediaProject/x264/releases/tag/0.164.r3194)), from  `libx264_0.164.r3194_msvc17.zip` to a x86(32 bit) dll project for Windows platform (written in c++) build by vs2022 but failed
(x264.lib can be linked and built successfullt)

My vs2022 solution contains a static library project and a dynamic library project
Project is using
```
C++ language standard: ISO C++ 17
C language standard: legacy MSVC

command line for .lib part:
/GS /W3 /Gy /I"D:\libjpeg-turbo\include\" /I"D:\libsodium\include\" /I"D:\libx264_msvc17\include" /I"D:\libyuv_win32\include\" /Zi /Od /fp:precise /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_UNICODE" /D "UNICODE" /WX- /Gd /Oi /MD /std:c++17 /Fa"Release\" /EHsc /nologo /Fo"Release\" /Ot /Fp"Release\hylibx.pch" /diagnostics:column 

command line for .dl part:
/permissive- /ifcOutput "DLL\Release\" /GS /GL /analyze- /W3 /Gy /Zc:wchar_t /Zi /Gm- /Od /sdl /Fd"DLL\Release\vc143.pdb" /Zc:inline /fp:precise /D "WIN32" /D "NDEBUG" /D "DLLTEST_EXPORTS" /D "_WINDOWS" /D "_USRDLL" /D "_WINDLL" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /Gd /Oy- /Oi /MD /std:c++17 /FC /Fa"DLL\Release\" /EHsc /nologo /Fo"DLL\Release\" /Fp"DLL\Release\DLLFrame.pch" /diagnostics:column 
```

However, libx264.lib from [0.164.r3107](https://github.com/ShiftMediaProject/x264/releases/tag/0.164.r3107) works without error

**Comment by Sibras** [comment]
A quick google search shows this appears to be a bug in visual studio itself due to changes in msvcrt between different version that causes issues. Either try updating your VS2022 install to the latest or try the msvc16 built version of the library

**Comment by JiaPai12138** [comment]
You are right, thanks for help!
After switching from version LTSC 17.10 to LTSC 17.12, problem solved!
