### ISSUE TITLE
Supporting dependency of P frame on I frame only

### ISSUE THREAD

**Issue by spaul13** [ShiftMediaProject/x264#6]
I have a doubt on x264 encoding which you have used. 

If I have IP_1P_2P_3 IPPP some kind of this GOP from the x264 encoded output. Then in general, P_3 will be dependent on I, P_1 and P_2, P_2 will be dependent on I and P_1 (a cumulative encoding).

**can you give me any ideas how can I support direct encoding so that all P_1, P_2, P_3 will be only dependent on the I frame?**

**Comment by Sibras** [comment]
This is the wrong location for questions such as that. For issues relating to x264 itself you should inquire through the official channels provided by the upstream x264 project (via videolan).
