### ISSUE TITLE
Can't use the builded vs project of x264

### ISSUE THREAD

**Issue by james20181013** [ShiftMediaProject/x264#7]
Dear all,
  I have two questions.
1, Whether the "x264cli.exe" you updated is generated by the x264 project you commited?
2, I built the vs project with the x264 sub folder named SMP, it can create sucessfully, and also can generate
h.264 stream, but the stream very differ with the stream generated by linux with the same encoder parameters. And at the same time, the value in the x264 like h->sps->i_mb_width is always be 0, but when I assign h->sps->i_mb_width to the local variable， the local variable can show the correct value. How can I generate the right h.264 stream with the vs project of x264.

**Comment by james20181013** [comment]
Dear all,  I use vs2013 to create the vs project

**Comment by Sibras** [comment]
1/ The cli executable on the release page is compiled directly from the provided VS projects in the SMP folder.

2/ The stream may differ if you are comparing different x264 versions but without knowing how they differ theres no way of knowing why they differ

"h->sps->i_mb_width" when you say its always zero how are you checking this value? If your using a debugger then its most likely that the debugger itself is just wrong and only detects the correct value when you assign it to a local variable (debuggers in release mode just dont work very well)

**Comment by james20181013** [comment]
Dear Sibras， Thanks very much for your reply.   I ensure that the linux and windows use the same version of x264 and use the same encoder parameters， in another word，I create the exe in linux and windows used the same x264 project downloaded from “https://github.com/ShiftMediaProject/x264”.
But the h.264 stream generated by linux and windows is different.  At the same time, the project was created by vs2013, information:
Microsoft Visual Studio Ultimate 2013
version 12.0.21005.1 REL
Microsoft .NET Framework
version 4.7.03056
the project can not shows the correct value like h->sps->i_mb_width, but when I assign h->sps->i_mb_width to the local variable， the local variable can show the correct value. 
Is there any problem of the version of vs2013?  Or could you please send me the information of vs you used to built the x264 windows project?

**Comment by james20181013** [comment]
Or I have made some mistakes during the project created?

**Comment by Sibras** [comment]
Does the version you compiled using VS2013 generate different bitstreams to the version you can download directly from the release page [https://github.com/ShiftMediaProject/x264/releases/download/0.157.r2932/x264_0.157.r2932.zip](https://github.com/ShiftMediaProject/x264/releases/download/0.157.r2932/x264_0.157.r2932.zip)?
The version from the release page is VS2017 but it shoudlnt really matter.

**Comment by james20181013** [comment]
I ensured three h.264 streams generated as follows:
1, Used the  libx264_0.157.r2932_msvc12\bin\x64\x264cli.exe
2, x264cli.exe generated by myselft in windows vs2013 with the x264 project downloaded from "https://github.com/ShiftMediaProject/x264" 
3, x264 generated by linux with the x264 project downloaded from "https://github.com/ShiftMediaProject/x264" 
All three exe used the same encoder parameters:
--input-res 960x448 -q 15 --no-deblock --frames 1 -o input_enc_960_448_0xf09b6100_seq2_yuv420p_1200kbps.h264 --ref 1 -b 0 --fps 30 --lookahead 0 --preset veryslow -I 90 --threads 1 --b-adapt 0 --scenecut 0 ./input_enc_960_448_0xf09b6100_seq2_yuv420p.yuv 

H.264 stream of Item 1 and Item 3 are the same, but both differ with item 2;

And when I used vs2017 to generate the x264cli.exe in windows, it could not generate libx264_10bd.lib, result in creating libx264.lib failure.
Is there any problem?  Looking forward to your reply.

**Comment by james20181013** [comment]
![1538041849 1](https://user-images.githubusercontent.com/43602590/46138225-e98f8e00-c27d-11e8-917c-aa99db6d8ddc.jpg)

**Comment by james20181013** [comment]
As the picture shows, the local_value assigned by h->sps->i_mb_width, local_value=60 is right, but the 
h->sps->i_mb_width = 0,  It is very weird!!

**Comment by Sibras** [comment]
OK so the supplied executable and the linux executable are both the same, so then clearly the error is in your VS2013 generated one. This may be a bug in VS2013 itself or your install is broken.

Ensure in VS that you are compiling in release mode when comparing different versions. If you cant compile in release mode even with VS2017 then its clearly an error with your installation (the provided x264cli.exe compiled fine in 2017).

> As the picture shows, the local_value assigned by h->sps->i_mb_width, local_value=60 is right, but the
> h->sps->i_mb_width = 0, It is very weird!!

h->sps->i_mb_width is probably==60 just the VS isnt displaying the correct value. This is just a debugger error and the code is most likely doing the correct thing.

**Comment by james20181013** [comment]
Dear Sibras，
    As you memtioned above, I checked the source code which I used to create the x264 vs2013 project, There were some bug modified by myself. Now I can generate h.264 stream when I use debug/release in window vs2013, and the h.264 stream is same as linux, the problem is fixed. Thanks a lot.   
    But now, when I select the debug mode, the problem still exists as I memtioned above:
As the picture shows, the local_value assigned by h->sps->i_mb_width, local_value=60 is right, but the
h->sps->i_mb_width = 0, It is very weird!!
    I tried other vs2013 in window with my colleague，the problem was also there. Maybe it is the debugger error, but I do not know how to fix that. So could you please give me some advice!  Looking forward to your reply!

**Comment by james20181013** [comment]
Does vs2017 debug mode can fix this problem?

**Comment by Sibras** [comment]
Its probably a VS2013 debug error. So theres nothing that can be done to fix it as its a bug in VS. Newer versions may fix it but youll have to try and find out.
Closing as no longer an issue with the code here.

**Comment by james20181013** [comment]
Okay， I will try in new vs version. Thanks a lot!
