### ISSUE TITLE
executable x264 not lib

### ISSUE THREAD

**Issue by khg2478** [ShiftMediaProject/x264#8]
Hi. I want to customize x264 source code for my research purpose and test the code with some parameters.

The current x264 project here compiles the source code into lib format but I want to test x264 source. Any suggestions to do so? I believe you must have done similar thing when you generated this project so..

Thanks a lot.

**Comment by Sibras** [comment]
The libx264 project will generate a lib. If you want to test the actual x264 executable then you need to compile the x264cli project
