### ISSUE TITLE
Integration with libav and GPAC

### ISSUE THREAD

**Issue by flickleafy** [ShiftMediaProject/x264#9]
I was playing around compiling x264 until I actually compiled it, and it seems to be working fine.

Well, not as I expected, because the usual x264 distributions actually are integrated with libav* formats (if compiled with lavf support, as it says when running x264.exe) and, GPAC for MP4 support.

I indeed gone to all websites that I found in Google, trying to find something useful telling how I could actually integrate that into x264cli, and I ended up with nothing. There is almost no useful information about how to integrate it, even using mingw, so, for Visual Studio there is even less information about how to make such kind of integration.

Can I ask you if you ever managed to compile x264 together both libav formats and GPAC (for MP4), all within Visual Studio?

Could you provide projects for Visual Studio for both, together x264?

**Comment by Sibras** [comment]
This build of x264 is used as a dependency for provided ffmpeg builds so having x264 depend on ffmpeg would result in a circular dependency that would cause all sorts of difficulties. As such there is no intention to support ffmpeg from within x264 as the assumption would be that if a user required that sort of support then they would use x264 through ffmpeg anyway.

**Comment by flickleafy** [comment]
That is funny, but I believe it is not what I said, never said ffmpeg. And second, the original x264 distributed everywhere do have that support... you should look on the interface of it... on the help option...

That is the x264 distribution that you can find anywhere....
https://prnt.sc/owbaqe

And that is the compiled version distributed in your site...
http://prntscr.com/owbbo1

I can say that even the file size of both have a huge difference...
